[package]
name = "tx-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1.4.0"
rust_decimal = { version = "1.40.0", features = ["serde-with-str"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
